version: '2'
services:
  web:
    build: .
    command: node-red
    ports:
      - "1880:1880"
    links:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mysql
