version: '2'
services:
  web:
    build: .
    command: node-red
    ports:
      - "1880:1880"
    links:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgre
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
